src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Ignore;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $siren;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $immatriculation_city;

    /**
     * @ORM\Column(type="datetime")
     */
    private $immatriculation_date;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $capital;

    /**
     * @ORM\ManyToOne(targetEntity=JuridicForm::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $form;

    /**
     * @ORM\OneToMany(targetEntity=Address::class, mappedBy="company", cascade={"persist"})
     */
    private $addresses;

    public function __construct()
    {
        $this->addresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    /**
     * For the serializer
     */
    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSiren(): ?string
    {
        return $this->siren;
    }

    public function setSiren(string $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getImmatriculationCity(): ?string
    {
        return $this->immatriculation_city;
    }

    public function setImmatriculationCity(string $immatriculation_city): self
    {
        $this->immatriculation_city = $immatriculation_city;

        return $this;
    }

    public function getImmatriculationDate(): ?\DateTimeInterface
    {
        return $this->immatriculation_date;
    }

    public function setImmatriculationDate(\DateTimeInterface $immatriculation_date): self
    {
        $this->immatriculation_date = $immatriculation_date;

        return $this;
    }

    public function getCapital(): ?string
    {
        return $this->capital;
    }

    public function setCapital(string $capital): self
    {
        $this->capital = $capital;

        return $this;
    }

    public function getForm(): ?JuridicForm
    {
        return $this->form;
    }

    public function setForm(?JuridicForm $form): self
    {
        $this->form = $form;

        return $this;
    }

    /**
     * @return Collection|Address[]
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): self
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses[] = $address;
            $address->setCompany($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): self
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getCompany() === $this) {
                $address->setCompany(null);
            }
        }

        return $this;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ["label" => "Nom"])
            ->add('siren', TextType::class)
            ->add('immatriculation_city',TextType::class, ["label" => "Ville d'immatriculation"])
            ->add('immatriculation_date', DateTimeType::class, ["label" => "Date d'immatriculation"])
            ->add('capital',TextType::class, ["label" => "Capital"])
            ->add('form');
            
        $builder->add('addresses', CollectionType::class, [
            'entry_type' => AddressType::class,
            'entry_options' => ['label' => false],
            'allow_add' => true,
            'by_reference' => false,
            'allow_delete' => true
        ]);
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Form\CompanyType;
use App\Manager\RollbackManager;
use App\Repository\CompanyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/", name="company_index", methods={"GET"})
     */
    public function index(CompanyRepository $companyRepository): Response
    {
        return $this->render('company/index.html.twig', [
            'companies' => $companyRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="company_new", methods={"GET","POST"})
     */
    public function new(Request $request, RollbackManager $rollback): Response
    {
        $company = new Company();
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // persist the object 
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($company);
            $entityManager->flush();

            // the object have an id, i can archive the version
            $rollback->save($company);

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_show", methods={"GET", "POST"})
     */
    public function show(Request $request, Company $company, RollbackManager $rollback): Response
    {
        $form = $this->createFormBuilder([])
            ->add('version', DateTimeType::class)
            ->add('save', SubmitType::class, ['label' => 'voir la version'])
            ->getForm();
 
        $form->handleRequest($request);

        
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $company = $rollback->restoreFrom($company,$data['version']);
        }


        return $this->render('company/show.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="company_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Company $company, RollbackManager $rollback): Response
    {
        $form = $this->createForm(CompanyType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rollback->save($company);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('company_index');
        }

        return $this->render('company/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="company_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Company $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('company_index');
    }
}

templates/company/_delete_form.html.twig
<form method="post" action="{{ path('company_delete', {'id': company.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/company/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.siren) }}
    {{ form_row(form.immatriculation_city) }}
    {{ form_row(form.immatriculation_date) }}
    {{ form_row(form.capital) }}
    {{ form_row(form.form) }}

    <h3>Adresses</h3>
    <ul class="addresses" data-prototype="{{ form_widget(form.addresses.vars.prototype)|e('html_attr') }}">
        <button type="button" class="add_item_link" data-collection-holder-class="addresses">Ajouter une adresse</button>
        {% for address in form.addresses %}
        <li>
            {{ form_row(address.number) }}
            {{ form_row(address.type) }}
            {{ form_row(address.name) }}
            {{ form_row(address.zipcode) }}
            {{ form_row(address.city) }}  
         
        </li>
        {% endfor %}
    </ul>

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/company/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer la société{% endblock %}

{% block body %}
    <h1>Modifier la société</h1>

    {{ include('company/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('company_index') }}">Retour à la liste</a>

    {{ include('company/_delete_form.html.twig') }}
{% endblock %}
{% block javascripts %}
<script>
    jQuery(document).ready(function () {
        // Get the ul that holds the collection of tags
        var $tagsCollectionHolder = $('ul.addresses');
        // count the current form inputs we have (e.g. 2), use that as the new
        // index when inserting a new item (e.g. 2)
        $tagsCollectionHolder.data('index', $tagsCollectionHolder.find('input').length);

        $collectionHolder = $('ul.addresses');

        // add a delete link to all of the existing tag form li elements
        $collectionHolder.find('li').each(function () {
            addTagFormDeleteLink($(this));
        });

        $('body').on('click', '.add_item_link', function (e) {
            var $collectionHolderClass = $(e.currentTarget).data('collectionHolderClass');
            // add a new tag form (see next code block)
            addFormToCollection($collectionHolderClass);
        })
    });

    function addFormToCollection($collectionHolderClass) {
        // Get the ul that holds the collection of tags
        var $collectionHolder = $('.' + $collectionHolderClass);

        // Get the data-prototype explained earlier
        var prototype = $collectionHolder.data('prototype');

        // get the new index
        var index = $collectionHolder.data('index');

        var newForm = prototype;
        // You need this only if you didn't set 'label' => false in your tags field in TaskType
        // Replace '__name__label__' in the prototype's HTML to
        // instead be a number based on how many items we have
        // newForm = newForm.replace(/__name__label__/g, index);

        // Replace '__name__' in the prototype's HTML to
        // instead be a number based on how many items we have
        newForm = newForm.replace(/__name__/g, index);

        // increase the index with one for the next item
        $collectionHolder.data('index', index + 1);

        // Display the form in the page in an li, before the "Add a tag" link li
        var $newFormLi = $('<li></li>').append(newForm);
        // Add the new form at the end of the list
        $collectionHolder.append($newFormLi)

        // add a delete link to the new form
        addTagFormDeleteLink($newFormLi);
    }


    function addTagFormDeleteLink($tagFormLi) {
        var $removeFormButton = $('<button type="button">Supprimer cette adresse</button>');
        $tagFormLi.append($removeFormButton);

        $removeFormButton.on('click', function (e) {
            // remove the li for the tag form
            $tagFormLi.remove();
        });
    }
</script>

{% endblock %}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}sociétés{% endblock %}

{% block body %}
    <h1>sociétés</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Siren</th>
                <th>Ville d'immatriculation</th>
                <th>Date d'immatriculation</th>
                <th>Capital</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for company in companies %}
            <tr>
                <td>{{ company.id }}</td>
                <td>{{ company.name }}</td>
                <td>{{ company.siren }}</td>
                <td>{{ company.immatriculationCity }}</td>
                <td>{{ company.immatriculationDate ? company.immatriculationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ company.capital }}</td>
                <td>
                    <a href="{{ path('company_show', {'id': company.id}) }}">voir</a>
                    <a href="{{ path('company_edit', {'id': company.id}) }}">editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Pas de société</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('company_new') }}">Ajouter</a>
{% endblock %}

templates/company/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle société{% endblock %}

{% block body %}
<h1>Nouvelle société</h1>

{{ include('company/_form.html.twig') }}

<a href="{{ path('company_index') }}">Retour à la liste</a>
{% endblock %}

{% block javascripts %}
<script>
      jQuery(document).ready(function () {
        // Get the ul that holds the collection of tags
        var $tagsCollectionHolder = $('ul.addresses');
        // count the current form inputs we have (e.g. 2), use that as the new
        // index when inserting a new item (e.g. 2)
        $tagsCollectionHolder.data('index', $tagsCollectionHolder.find('input').length);

        $collectionHolder = $('ul.addresses');

        // add a delete link to all of the existing tag form li elements
        $collectionHolder.find('li').each(function () {
            addTagFormDeleteLink($(this));
        });

        $('body').on('click', '.add_item_link', function (e) {
            var $collectionHolderClass = $(e.currentTarget).data('collectionHolderClass');
            // add a new tag form (see next code block)
            addFormToCollection($collectionHolderClass);
        })
    });

    function addFormToCollection($collectionHolderClass) {
        // Get the ul that holds the collection of tags
        var $collectionHolder = $('.' + $collectionHolderClass);

        // Get the data-prototype explained earlier
        var prototype = $collectionHolder.data('prototype');

        // get the new index
        var index = $collectionHolder.data('index');

        var newForm = prototype;
        // You need this only if you didn't set 'label' => false in your tags field in TaskType
        // Replace '__name__label__' in the prototype's HTML to
        // instead be a number based on how many items we have
        // newForm = newForm.replace(/__name__label__/g, index);

        // Replace '__name__' in the prototype's HTML to
        // instead be a number based on how many items we have
        newForm = newForm.replace(/__name__/g, index);

        // increase the index with one for the next item
        $collectionHolder.data('index', index + 1);

        // Display the form in the page in an li, before the "Add a tag" link li
        var $newFormLi = $('<li></li>').append(newForm);
        // Add the new form at the end of the list
        $collectionHolder.append($newFormLi)

        // add a delete link to the new form
        addTagFormDeleteLink($newFormLi);
    }


    function addTagFormDeleteLink($tagFormLi) {
        var $removeFormButton = $('<button type="button">Supprimer cette adresse</button>');
        $tagFormLi.append($removeFormButton);

        $removeFormButton.on('click', function (e) {
            // remove the li for the tag form
            $tagFormLi.remove();
        });
    }
</script>

{% endblock %}

templates/company/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Société{% endblock %}

{% block body %}
<h1>Société</h1>
{{ form(form) }}

{% if company %}



<table class="table">
    <tbody>
        <tr>
            <th>Id</th>
            <td>{{ company.id }}</td>
        </tr>
        <tr>
            <th>Noms</th>
            <td>{{ company.name }}</td>
        </tr>
        <tr>
            <th>Siren</th>
            <td>{{ company.siren }}</td>
        </tr>
        <tr>
            <th>Ville d'immatriculation</th>
            <td>{{ company.immatriculationCity }}</td>
        </tr>
        <tr>
            <th>date d'immatriculation</th>
            <td>{{ company.immatriculationDate ? company.immatriculationDate|date('Y-m-d H:i:s') : '' }}</td>
        </tr>
        <tr>
            <th>Capital</th>
            <td>{{ company.capital }}</td>
        </tr>
        <tr>
            <th>Forme Juridique</th>
            <td>{{ company.form }}</td>
        </tr>
        <tr>
            <th>Adresses</th>
            <td>
                <ul>
                    {% for address in company.addresses %}
                    <li>
                        {{ address.number }}
                        {{ address.type }}
                        {{ address.name }}
                        {{ address.zipcode }}
                        {{ address.city }}
                    </li>
                    {% endfor %}
            </td>
        </tr>
    </tbody>
</table>


<a href="{{ path('company_index') }}">retour à la liste</a>

<a href="{{ path('company_edit', {'id': company.id}) }}">modifier</a>

{{ include('company/_delete_form.html.twig') }}
{% else %}
La companie n'a pas encore été saisie !!
{% endif %}

{% endblock %}